config/routes.rb
Rails.application.routes.draw do
  
  namespace "api" do
    resources :channels, only: [:show], defaults: {format: :json} do
      member do 
        get "raw"
      end
    end
  end
  
  resources :channels do
    resources :tweets 
    
    member do 
      get "rerun_query"
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :tweets, only: [:show]
  
  root "channels#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/channel.rb
class Channel < ApplicationRecord
  has_many :tweets
  
  def self.test_exception
    1 / 0
  end
  
  def last_query
    tweets.order("created_at desc").limit(1)[0]; 
  end
  
  def self.client
    @client ||= Twitter::REST::Client.new do |config|
      # first two params are used in application-only authentication
      config.consumer_key        = ENV["TWITTER_CONSUMER_KEY"] 
      config.consumer_secret     = ENV["TWITTER_CONSUMER_SECRET"] 
      
      # Some resources require single-user authentication, in which case we include the following
      # config.access_token        = ENV["TWITTER_ACCESS_TOKEN"]
      # config.access_token_secret = ENV["TWITTER_ACCESS_SECRET"]
    end
  end
  
  
  def rerun_query # twitter search API
    puts "  Fetching twitter data for #{ self.name }"
    # Requests / 15-min window (app auth)	
    if self.keyword.present?
      # go to apps.twitter.com to add an app and generate these keys and tokens
      
      tweets = Channel.client.search(self.keyword, result_type: "recent", count: 100).collect do |tweet|
        # puts tweet.favorite_count
        # puts tweet.retweet_count
        # puts tweet.full_text
        # puts tweet    e.g.  <Twitter::Tweet:0x007f9ef54c4f78>
        # puts tweet.to_json # {...}

        tweet
      end
      
      self.tweets.create( keyword: self.keyword, unique_id:  nil, full_json: tweets.to_json)
    end
  end
  
end

app/models/tweet.rb
# originally named tweet, this is probably more appropriately named "queries"

class Tweet < ApplicationRecord
  belongs_to :channel
  before_save :update_statistics
  
  
  def parsed_json
    @parsed_json ||= JSON.parse(self.full_json)
  end
   
  def unique_tweets_per_hour
    (1.0 * n_unique_tweets / time_span).round
  end
  
  def followers_reached_per_hour
    (parsed_json.collect {|e| e["user"]["followers_count"] }.sum.to_f / time_span).round
    
  end
  
  def n_unique_tweets
    parsed_json.uniq {|e| e["text"].gsub(/\d/, "0").gsub(/^RT @.*?: /, "")}.size  
  end
  
  def time_span
    earliest_at = Time.parse( parsed_json.last["created_at"] )
    latest_at = Time.parse( parsed_json.first["created_at"] )
    (latest_at - earliest_at) / 1.hour
  end
  
  def statistics
    a = read_attribute(:statistics_json)
    a == nil ? nil : JSON.parse(a)
  end
  
  def statistics=( obj )
    write_attribute(:statistics_json, obj.to_json )
  end
  
  private
  
  def update_statistics
    self.statistics = {
      "unique_tweets_per_hour" => self.unique_tweets_per_hour,
      "followers_reached_per_hour" => self.followers_reached_per_hour,
      "earliest_at" => Time.parse( self.parsed_json.last["created_at"] ),
      "latest_at" => Time.parse( self.parsed_json.first["created_at"] ),
      "n_tweets" => self.parsed_json.size,
      "n_unique_tweets" => self.n_unique_tweets
    }
  end
end

app/controllers/api/channels_controller.rb
class Api::ChannelsController < ApplicationController
  before_action :set_channel, only: [:show, :raw]

  # GET /channels
  # GET /channels.json



  # GET /channels/1
  # GET /channels/1.json
  def show
  end


  def raw
  end
  


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_channel
      @channel = Channel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    # def tweet_params
    #   params.require(:tweet).permit(:keyword, :unique_id, :full_json, :channel_id)
    # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  before_action :set_channel, only: [:show, :edit, :update, :destroy, :rerun_query]


  def rerun_query
    @channel.rerun_query

    
    redirect_to channel_tweets_path(@channel), notice: "Query was re-run"
  end
  
  # GET /channels
  # GET /channels.json
  def index
    @channels = Channel.all
  end

  # GET /channels/1
  # GET /channels/1.json
  def show
    redirect_to channel_tweets_path(@channel)
  end

  # GET /channels/new
  def new
    @channel = Channel.new(active: true)
  end

  # GET /channels/1/edit
  def edit
  end

  # POST /channels
  # POST /channels.json
  def create
    @channel = Channel.new(channel_params)

    respond_to do |format|
      if @channel.save
        format.html { redirect_to @channel, notice: 'Channel was successfully created.' }
        format.json { render :show, status: :created, location: @channel }
      else
        format.html { render :new }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /channels/1
  # PATCH/PUT /channels/1.json
  def update
    respond_to do |format|
      if @channel.update(channel_params)
        format.html { redirect_to @channel, notice: 'Channel was successfully updated.' }
        format.json { render :show, status: :ok, location: @channel }
      else
        format.html { render :edit }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /channels/1
  # DELETE /channels/1.json
  def destroy
    @channel.destroy
    respond_to do |format|
      format.html { redirect_to channels_url, notice: 'Channel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_channel
      @channel = Channel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def channel_params
      params.require(:channel).permit(:name, :keyword, :symbol, :active)
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  # GET /tweets
  # GET /tweets.json
  def index
    

    if params[:channel_id].present? 
      @channel = Channel.find(params[:channel_id])
    end
    
    # avoid including full_json because if there are many records requires a lot of memory
    @tweets = @channel ? @channel.tweets.where("created_at > ?", Time.now - 7.days ).order("created_at ASC").select("id, keyword, created_at, channel_id, statistics_json") : Tweet.all
    @exchange_rates = ExchangeRate.where("created_at > ?", Time.now - 7.days ).order("created_at ASC")
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:keyword, :unique_id, :full_json, :channel_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/channels/_form.html.erb
<%= form_with(model: channel, local: true) do |form| %>
  <% if channel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(channel.errors.count, "error") %> prohibited this channel from being saved:</h2>

      <ul>
      <% channel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, id: :channel_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :keyword, "Search keyword(s)" %>
    <%= form.text_field :keyword, id: :channel_keyword, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :symbol %>
    <%= form.text_field :symbol, id: :channel_symbol, class: "form-control" %>
  </div>
  
  <div class="form-group">
    <%= form.check_box :active, id: :channel_active %>
    <%= form.label :active, "Actively update this channel" %>
  </div>


  <div class="actions">
    <%= form.submit nil, class: "btn btn-default" %>
  </div>
<% end %>

app/views/channels/edit.html.erb
<h1>Editing Channel</h1>

<%= render 'form', channel: @channel %>
<br />
<br />
<%= link_to 'Show', @channel %> |
<%= link_to 'Back', channels_path %>

app/views/channels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Channels</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Symbol</th>
      <th>Search Keyword(s)</th>
      <th>Last query at</th>
      <th>Mentions per hour</th>
      <th>Last exchange rate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @channels.each do |channel| %>
      <tr class="<%= "success" if channel.active %>">
        <td><%= channel.name %></td>
        <td><%= channel.symbol %></td>
        <td><%= channel.keyword %></td>
        <td><%= t = channel.tweets.order("created_at desc").limit(1).select("full_json,created_at")[0]; 
          t ? "#{time_ago_in_words(t.created_at)} ago" : "none" %></td>
        <td><%= t ? t.unique_tweets_per_hour : "" %></td>
        <td><%= r=ExchangeRate.recent_price_of(channel.symbol, Time.now, 30.minutes); r ? "#{r} USD" : nil %></td>
        <td><%= link_to 'Show', channel_tweets_path(channel), class: "btn btn-default btn-xs" %></td>
        <td><%= link_to 'Show features json', api_channel_path(channel), class: "btn btn-default btn-xs" %></td>
        <td><%= link_to 'Edit', edit_channel_path(channel), class: "btn btn-default btn-xs" %></td>
        <td><%# link_to 'Destroy', channel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Channel', new_channel_path, class: "btn btn-default" %>

app/views/channels/new.html.erb
<h1>New Channel</h1>

<%= render 'form', channel: @channel %>
<br />
<%= link_to 'Back', channels_path %>

app/views/channels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Keyword:</strong>
  <%= @channel.keyword %>
</p>

<%= link_to 'Edit', edit_channel_path(@channel) %> |
<%= link_to 'Back', channels_path %>