config/routes.rb
Rails.application.routes.draw do
  
  namespace "api" do
    resources :channels, only: [:show], defaults: {format: :json} do
      member do 
        get "raw"
      end
    end
  end
  
  resources :channels do
    resources :tweets 
    
    member do 
      get "rerun_query"
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :tweets, only: [:show]
  
  root "channels#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/channel.rb
class Channel < ApplicationRecord
  has_many :tweets
  
  def self.test_exception
    1 / 0
  end
  
  def last_query
    tweets.order("created_at desc").limit(1)[0]; 
  end
  
  def self.client
    @client ||= Twitter::REST::Client.new do |config|
      # first two params are used in application-only authentication
      config.consumer_key        = ENV["TWITTER_CONSUMER_KEY"] 
      config.consumer_secret     = ENV["TWITTER_CONSUMER_SECRET"] 
      
      # Some resources require single-user authentication, in which case we include the following
      # config.access_token        = ENV["TWITTER_ACCESS_TOKEN"]
      # config.access_token_secret = ENV["TWITTER_ACCESS_SECRET"]
    end
  end
  
  
  def rerun_query # twitter search API
    puts "  Fetching twitter data for #{ self.name }"
    # Requests / 15-min window (app auth)	
    if self.keyword.present?
      # go to apps.twitter.com to add an app and generate these keys and tokens
      
      tweets = Channel.client.search(self.keyword, result_type: "recent", count: 100).collect do |tweet|
        # puts tweet.favorite_count
        # puts tweet.retweet_count
        # puts tweet.full_text
        # puts tweet    e.g.  <Twitter::Tweet:0x007f9ef54c4f78>
        # puts tweet.to_json # {...}

        tweet
      end
      
      self.tweets.create( keyword: self.keyword, unique_id:  nil, full_json: tweets.to_json)
    end
  end
  
end

app/models/tweet.rb
# originally named tweet, this is probably more appropriately named "queries"

class Tweet < ApplicationRecord
  belongs_to :channel
  before_save :update_statistics
  
  
  def parsed_json
    @parsed_json ||= JSON.parse(self.full_json)
  end
   
  def unique_tweets_per_hour
    (1.0 * n_unique_tweets / time_span).round
  end
  
  def followers_reached_per_hour
    (parsed_json.collect {|e| e["user"]["followers_count"] }.sum.to_f / time_span).round
    
  end
  
  def n_unique_tweets
    parsed_json.uniq {|e| e["text"].gsub(/\d/, "0").gsub(/^RT @.*?: /, "")}.size  
  end
  
  def time_span
    earliest_at = Time.parse( parsed_json.last["created_at"] )
    latest_at = Time.parse( parsed_json.first["created_at"] )
    (latest_at - earliest_at) / 1.hour
  end
  
  def statistics
    a = read_attribute(:statistics_json)
    a == nil ? nil : JSON.parse(a)
  end
  
  def statistics=( obj )
    write_attribute(:statistics_json, obj.to_json )
  end
  
  private
  
  def update_statistics
    self.statistics = {
      "unique_tweets_per_hour" => self.unique_tweets_per_hour,
      "followers_reached_per_hour" => self.followers_reached_per_hour,
      "earliest_at" => Time.parse( self.parsed_json.last["created_at"] ),
      "latest_at" => Time.parse( self.parsed_json.first["created_at"] ),
      "n_tweets" => self.parsed_json.size,
      "n_unique_tweets" => self.n_unique_tweets
    }
  end
end

app/controllers/api/channels_controller.rb
class Api::ChannelsController < ApplicationController
  before_action :set_channel, only: [:show, :raw]

  # GET /channels
  # GET /channels.json



  # GET /channels/1
  # GET /channels/1.json
  def show
  end


  def raw
  end
  


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_channel
      @channel = Channel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    # def tweet_params
    #   params.require(:tweet).permit(:keyword, :unique_id, :full_json, :channel_id)
    # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  before_action :set_channel, only: [:show, :edit, :update, :destroy, :rerun_query]


  def rerun_query
    @channel.rerun_query

    
    redirect_to channel_tweets_path(@channel), notice: "Query was re-run"
  end
  
  # GET /channels
  # GET /channels.json
  def index
    @channels = Channel.all
  end

  # GET /channels/1
  # GET /channels/1.json
  def show
    redirect_to channel_tweets_path(@channel)
  end

  # GET /channels/new
  def new
    @channel = Channel.new(active: true)
  end

  # GET /channels/1/edit
  def edit
  end

  # POST /channels
  # POST /channels.json
  def create
    @channel = Channel.new(channel_params)

    respond_to do |format|
      if @channel.save
        format.html { redirect_to @channel, notice: 'Channel was successfully created.' }
        format.json { render :show, status: :created, location: @channel }
      else
        format.html { render :new }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /channels/1
  # PATCH/PUT /channels/1.json
  def update
    respond_to do |format|
      if @channel.update(channel_params)
        format.html { redirect_to @channel, notice: 'Channel was successfully updated.' }
        format.json { render :show, status: :ok, location: @channel }
      else
        format.html { render :edit }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /channels/1
  # DELETE /channels/1.json
  def destroy
    @channel.destroy
    respond_to do |format|
      format.html { redirect_to channels_url, notice: 'Channel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_channel
      @channel = Channel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def channel_params
      params.require(:channel).permit(:name, :keyword, :symbol, :active)
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  # GET /tweets
  # GET /tweets.json
  def index
    

    if params[:channel_id].present? 
      @channel = Channel.find(params[:channel_id])
    end
    
    # avoid including full_json because if there are many records requires a lot of memory
    @tweets = @channel ? @channel.tweets.where("created_at > ?", Time.now - 7.days ).order("created_at ASC").select("id, keyword, created_at, channel_id, statistics_json") : Tweet.all
    @exchange_rates = ExchangeRate.where("created_at > ?", Time.now - 7.days ).order("created_at ASC")
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:keyword, :unique_id, :full_json, :channel_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_form.html.erb
<%= form_with(model: tweet, local: true) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :keyword %>
    <%= form.text_field :keyword, id: :tweet_keyword %>
  </div>



  <div class="field">
    <%= form.label :channel_id %>
    <%= form.select :channel_id, Channel.all.collect {|c| [ c.name, c.id ] }, id: :tweet_channel_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>

<%= link_to "Features API", api_channel_path(@channel), class: "btn btn-default pull-right" %>

<h1>Queries<%= " for #{@channel.name} (#{@channel.symbol})" if @channel %></h1>


<div id="chart_div" style="width: 900px; height: 300px"></div>

    <script type="text/javascript">
      google.charts.load('current', {'packages':['corechart', "line"]});
      google.charts.setOnLoadCallback(drawChart);

      function drawChart() {

        var data = new google.visualization.DataTable();
        data.addColumn('date', 'Date');
        data.addColumn('number', 'Mentions per hour');
        data.addColumn('number', 'Sum followers reached per hour');
        data.addColumn('number', 'Price in USD');

        data.addRows(<%= 
          (
            @tweets.collect {|t| [
              t.created_at, 
              t.statistics["unique_tweets_per_hour"], 
              t.statistics["followers_reached_per_hour"],
              nil, 
            ]} +
            @exchange_rates.collect {|t| [
              t.created_at, 
              nil, 
              nil,
              t.price_of(@channel.symbol)
            ]}
          ).to_json.html_safe %>
          .map(function(e) {return [new Date(e[0]), e[1], e[2], e[3]]}))

        var options = {
          // title: 'Tweets per hour',
          width: 900,
          height: 250,
          curveType: "function",
          hAxis: {
            format: 'M/d/yy H:mm',
            gridlines: {count: 15}
          },
          vAxis: {
            gridlines: {color: 'none'},
            minValue: 0
          },
          series: {
              0: {axis: 'n'},
              1: {axis: 'n2'},
              2: {axis: 'price'}
            },
          axes: {
            y: {
              'n': {label: 'Mentions per hour'},
              'n2': {label: 'Followers reached per hour'},
              'price': {label: 'Price in USD', format: 'currency'}
            }
          },
        };
        var materialChart = new google.charts.Line(document.getElementById('chart_div'));
        materialChart.draw(data, google.charts.Line.convertOptions(options));

        // var chart = new google.visualization.LineChart(document.getElementById('chart_div'));

        // chart.draw(data, options);
      }

</script>
      
<table class="table">
  <thead>
    <tr>
      <th>n Results</th>
      <th>Result posted time-range</th>
      <th>Query performed at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tweets.each do |tweet| %>
    
    <%
    

    earliest_at = Time.parse(tweet.statistics["earliest_at"])
    latest_at = Time.parse(tweet.statistics["latest_at"])
    
    %>
      <tr>
        <td><%= tweet.statistics["n_tweets"] %> 
          (<%= tweet.statistics["n_unique_tweets"] %> unique text)
        </td>
        <td><%= earliest_at.strftime("%Y-%m-%d %H:%M") if earliest_at %> &mdash; 
          <%= latest_at.strftime(earliest_at.to_date == latest_at.to_date ? "%H:%M" : "%m-%d %H:%M") if latest_at %>
        </td>
        <td><%= time_ago_in_words( tweet.created_at ) %> ago</td>
        <td><%= link_to 'Show', tweet %></td>
        <td><%= link_to 'Show Expanded', "#{tweet_path(tweet)}?expanded=t" %></td>
        <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if @channel %>
<%= link_to "Rerun query", rerun_query_channel_path( @channel ), class: "btn btn-default" %>
<% end %>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Keyword:</strong>
  <%= @tweet.keyword %>
</p>




<%
  
  omit_keys = ["created_at", "id", "text", "truncated", "possibly_sensitive", "profile_image_url", "profile_image_url_https", "profile_banner_url", "profile_sidebar_fill_color", "profile_background_image_url_https", "profile_background_tile", "profile_background_image_url", "profile_link_color", "profile_sidebar_border_color", "profile_text_color", "profile_use_background_image", "has_extended_profile", "in_reply_to_status_id_str", "in_reply_to_user_id_str", "contributors", "geo", "entities", "is_quote_status"]
  
%>
<table class="table">
  <tr>
    <th style="min-width: 200px; ">Created at</th>
    <th>Text</th>
    <th style="min-width: 250px; ">Statistics</th>
    <th></th>
  </tr>
  <% (@tweet.parsed_json || []).group_by {|t| t["text"]}.each do |text, tweets| %>

  <tr>
    <td><%= tweets.last["created_at"] %></td>
    <td><%= text.gsub(/^RT @.*?: /, "") %></td>    
    <td>
      <ul>
      <li>Language: <%= tweets[0]["lang"] %></li>
      <li>RT: <%= tweets[0]["retweet_count"] %></li>
      <% tweets.each do |tweet| %>
        <li>User: <%= tweet["user"]["name"] %></li>
        <ul>
          <li>Favs: <%= tweet["favorite_count"] %></li>
      
          <li>User followers: <%= tweet["user"]["followers_count"] %></li>
          <li>User statuses: <%= tweet["user"]["statuses_count"] %></li>

        </ul>
      
      <% end %>
      </ul>
      
    </td>
    <td>
      <% if params[:expanded] == "t" %>

        <table class="table">

        <% tweets[0].select {|k,v| !omit_keys.include?(k)}.each do |k,v| %>
          <tr>
            <td><%= k %></td>
            <td><%= v.class == Hash ? v.select {|k,v| !omit_keys.include?(k)} : v %></td>
          </tr>
        <% end %>
        </table>

      <% end %>
    </td>
  </tr>
  <% end %>
</table>

<%# link_to 'Edit', edit_tweet_path(@tweet) %> |
<%# link_to 'Back', tweets_path %>